// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzwi-RissKRckU_hC-jJ5sufm0TB13Qs',
    appId: '1:818698599963:web:0f24ac8149a1e7b35082be',
    messagingSenderId: '818698599963',
    projectId: 'my-todo-0012',
    authDomain: 'my-todo-0012.firebaseapp.com',
    storageBucket: 'my-todo-0012.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvGY6gDxOw_O8btdLlZenhMc6bSzcmo4',
    appId: '1:818698599963:android:e34095f5ed50b8ab5082be',
    messagingSenderId: '818698599963',
    projectId: 'my-todo-0012',
    storageBucket: 'my-todo-0012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMlHYdXZw2aLxWrhuQ6xBMKm4vaVB6E7E',
    appId: '1:818698599963:ios:6602fe55cceff3b75082be',
    messagingSenderId: '818698599963',
    projectId: 'my-todo-0012',
    storageBucket: 'my-todo-0012.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMlHYdXZw2aLxWrhuQ6xBMKm4vaVB6E7E',
    appId: '1:818698599963:ios:6602fe55cceff3b75082be',
    messagingSenderId: '818698599963',
    projectId: 'my-todo-0012',
    storageBucket: 'my-todo-0012.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFzwi-RissKRckU_hC-jJ5sufm0TB13Qs',
    appId: '1:818698599963:web:675cd191e8a79f645082be',
    messagingSenderId: '818698599963',
    projectId: 'my-todo-0012',
    authDomain: 'my-todo-0012.firebaseapp.com',
    storageBucket: 'my-todo-0012.firebasestorage.app',
  );
}
